# Generated by Django 4.2.7 on 2023-11-30 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_order_remove_product_categories_orderitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='description',
        ),
    ]
